apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-server-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-server-app
  template:
    metadata:
      labels:
        app: my-server-app
    spec:
      containers:
        - name: my-server-app
          image: sjarunvenkat/mongoserver:latest
          ports:
            - containerPort: 6039
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb-service:27017/serverdb"
