apiVersion: v1
kind: Service
metadata:
  name: my-server-app-service
spec:
  selector:
    app: my-server-app
  ports:
    - protocol: "TCP"
      port: 6039
      targetPort: 6039
  type: NodePort
